@BASE_URL = http://127.0.0.1:8000


###
# register.user
POST {{BASE_URL}}/api/auth/register
Content-Type: application/json

{
    "email": "abc123@naver.com",
    "name": "sjahn",
    "password": "rewq1234"
}


###
# @name login
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
    "email": "asj214@naver.com",
    "password": "rewq1234"
}


###
@token = {{ login.response.body.token }}


###
# auth.me
GET {{BASE_URL}}/api/auth/me
Content-Type: application/json
Authorization: Bearer {{ token }}


###
# categories.list
GET {{BASE_URL}}/api/categories
Content-Type: application/json
Authorization: Bearer {{ token }}


###
# categories.create
POST {{BASE_URL}}/api/categories
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "parent_id": null,
    "name": "테스트",
    "order": 3,
    "depth": 1
}

###
# categories.create
POST {{BASE_URL}}/api/categories
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "parent_id": 5,
    "name": "소프트웨어 개발",
    "order": 2,
    "depth": 2
}


###
# categories.retrieve
GET {{BASE_URL}}/api/categories/2
Content-Type: application/json
Authorization: Bearer {{ token }}


###
# categories.update
PUT {{BASE_URL}}/api/categories/2
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "name": "페인트 시공"
}


###
# categories.destroy
DELETE {{BASE_URL}}/api/categories/11
Content-Type: application/json
Authorization: Bearer {{ token }}


###
# products.list
GET {{BASE_URL}}/api/products?page=1&per_page=5
Content-Type: application/json
Authorization: Bearer {{ token }}


###
# products.create
POST {{BASE_URL}}/api/products
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "category_id": 8,
    "name": "상품 등록 테스트",
    "amount": 35000,
    "description": "상품 상세 정보입니다."
}


###
# products.retrieve
GET {{BASE_URL}}/api/products/31
Content-Type: application/json
Authorization: Bearer {{ token }}


###
# products.update
PUT {{BASE_URL}}/api/products/31
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "name": "웨딩 사진 촬영 전문가",
    "amount": 120000
}


###
# products.destroy
DELETE {{BASE_URL}}/api/products/31
Content-Type: application/json
Authorization: Bearer {{ token }}


###
# purchases.list
GET {{BASE_URL}}/api/purchases
Content-Type: application/json
Authorization: Bearer {{ token }}



###
# purchases.create
POST {{BASE_URL}}/api/purchases
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "purchases": [
        {
            "product_id": 2
        }
    ]
}