# Generated by Django 4.0.2 on 2022-03-01 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent',
                 models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                   related_name='children', to='categories.category')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING,
                                           related_name='categories', to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=256, verbose_name='카테고리명')),
                ('path', models.JSONField(default=None, null=True, verbose_name='카테고리 경로')),
                ('depth', models.IntegerField(default=1, verbose_name='뎁스')),
                ('order', models.IntegerField(default=1, verbose_name='정렬순위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['depth', 'order'],
            },
        ),
    ]
