# Generated by Django 4.0.2 on 2022-03-01 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING,
                                           related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING,
                                              related_name='purchases', to='products.product')),
                ('status', models.CharField(
                    choices=[('PAYMENT_REQUEST', 'PAYMENT_REQUEST'), ('PAYMENT_COMPLETE', 'PAYMENT_COMPLETE'),
                             ('PAYMENT_FAILED', 'PAYMENT_FAILED'), ('REFUND_REQUEST', 'REFUND_REQUEST'),
                             ('REFUND_COMPLETE', 'REFUND_COMPLETE'), ('REFUND_REJECT', 'REFUND_REJECT')],
                    default='PAYMENT_REQUEST', max_length=50, verbose_name='결제 상태')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='구매 시 금액')),
                ('completed_at', models.DateTimeField(default=None, null=True, verbose_name='결제 완료 날짜')),
                ('refund_request_at', models.DateTimeField(default=None, null=True, verbose_name='환불 요청 날짜')),
                ('refund_completed_at', models.DateTimeField(default=None, null=True, verbose_name='환불 처리 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ['-id'],
            },
        ),
    ]
